Update dependencies and makefile
luizalabs/django-toolkit pull request #32
Opened 2018-10-03 01:05 UTC by ariadyne-luizalabs

2018-10-03 12:20 UTC, gilmarsoares-luizalabs requested changes
🚨 Build falhando, verificar por favor.

2018-10-03 12:20 UTC, vitorcapuano-luizalabs requested changes
🚨 Build falhando, verificar por favor.

2018-10-03 17:09 UTC, adlermedrado commented
🚨 Build falhando, verificar por favor.

2018-10-04 22:42 UTC, jairhenrique approved these changes

2018-10-05 12:53 UTC, spacexnu approved these changes

2018-10-05 12:56 UTC, gilmarsoares-luizalabs approved these changes

2018-10-05 13:09 UTC, vitorcapuano-luizalabs approved these changes

2018-10-05 19:41 UTC, merged